repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.300
    hooks:
      - id: pyright
        args: ["snapstream"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: [".[toml]"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.1
    hooks:
      - id: poetry-check
