name: Test Python Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: "1.4.2"

      - name: Install package
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Activate virtualenv unix
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Activate virtualenv windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          .\.venv\Scripts\Activate.ps1
          $env:PATH | Out-File -FilePath $GITHUB_ENV -Append

      - name: Run linting & tests
        run: |
          bandit -c pyproject.toml .
          pydocstyle .
          pyright .
          flake8 .
          pytest .
